name: Build and Push Docker Image

on: push

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest

    steps:

    - name: Build Docker Image
      run: |
        docker build -t testing:latest -f /Zadatak4/projekat/Dockerfile /Zadatak4/projekat/

    # - name: Log in to Docker Hub
    #   run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

    # - name: Push Docker Image to Docker Hub
    #   run: docker push your-image-name:latest