name: Echo Message on Push

on: push

jobs:
  echo-message:
    runs-on: ubuntu-latest

    steps:
    # - name: Checkout Repository
    #   uses: actions/checkout@v2

    - name: Echo Message
      run: |
        echo "ova poruka ce da se izvrsi svaki put kad se uradi push"